baseurl: "https://example.org/"
title: "Midwest Undergraduate Data Analytics Competition"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: "UA-9232216-1"

params:
  # Conference info
  Name: "MUDAC 2018"
  Description: "Midwest Undergraduate Data Analytics Competition"
  Date: "April 7-8"
  # Price: "Only $50 Per Team" # If your event is free, just comment this line
  Venue: "Winona State University"
  Address: "175 W Mark St"
  City:  "Winona"
  State: "MN"
  Images: ["/img/badge.jpg"]
  GoogleMapsKey: "AIzaSyDIqO4CvjwGI0tOPlFRsp01aCf6FR6Dy_U"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - location
    #- speakers
    - schedule
      #- sponsors
      # - partners
    #- contact

  # Titles which you can translate to other languages
  Titles:
    about: "About"
    location: "Location"
    speakers: "Speakers"
    schedule: "Schedule"
    sponsors: "Sponsors"
    partners: "Partners"
    contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  #   CallToAction:
  #     text: "Register now!"
  #     link: "http://register.example.com"
  # 
  # Fork me on GitHub, if you don't want this, just remove the forkButton property
  # ForkButton:
  #   repository: "https://github.com/jweslley/hugo-conference/"

  # List of Sponsors
  Sponsors:
    - name: "Hugo"
      logo: "/img/hugo.png"
      url: "http://gohugo.io"

  # List of Partners
  Partners:
    - name: "Hugo"
      logo: "/img/hugo.jpg"
      url: "https://gohugo.io"
    - name: "BrazilJS"
      logo: "/img/partner.png"
      url: "http://braziljs.org"

  # The entire schedule
  Schedule:

    - time: "Saturday April 7 9:30 AM "
      name: "Participant Registration Begins"

    - time: "Saturday April 7 10:30 AM"
      name: "Discussion of Contest Rules"

    - time: "Saturday April 7 11:00 AM"
      name: "Meet & Greet the Data"

    - time: "Saturday April 7 12:00 PM"
      name: "Competition Begins"

    - time: "Saturday April 7 6:00 PM"
      name: "Dinner / Panel Discussion"

    - time: "Saturday April 7 7:30 PM"
      name: "Competition Resumes"

    - time: "Sunday April 8 9:30AM"
      name: "Judge Registration"

    - time: "Sunday April 8 9:45AM"
      name: "Judge Orientation / Greet the Data"

    - time: "Sunday April 8 10:30 AM"
      name: "All presentations/slides are due"

    - time: "Sunday April 8 11:15 AM"
      name: "Judging - Round 1 /Job Fair"

    - time: "Sunday April 8 2:30 PM"
      name: "Judging - Round 2 /Job Fair"


    - time: "Sunday April 8 3:30 PM"
      name: "Reception"

    - time: "Sunday April 8 4:00 PM"
      name: "Awards Ceremony"

